#import <Foundation/Foundation.h>
#import "PBTimezone.h"
#import "PBTimezoneLocation.h"
#import "PBApi.h"

/**
* Location Intelligence APIs
* Incorporate our extensive geodata into everyday applications, business processes and workflows.
*
* OpenAPI spec version: 6.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface PBLIAPIGeoTimeServiceApi: NSObject <PBApi>

extern NSString* kPBLIAPIGeoTimeServiceApiErrorDomain;
extern NSInteger kPBLIAPIGeoTimeServiceApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Timezone By Address.
/// Identifies and retrieves the local time of any location in the world for a given address and time. The input and retrieved time format is in milliseconds.
///
/// @param timestamp Timestamp in miliseconds.
/// @param address The address to be searched.
/// @param matchMode Match modes determine the leniency used to make a match between the input address and the reference data. (optional) (default to Relaxed)
/// @param country Country ISO code. (optional) (default to USA)
/// 
///  code:200 message:"successful operation"
///
/// @return PBTimezone*
-(NSNumber*) getTimezoneByAddressWithTimestamp: (NSString*) timestamp
    address: (NSString*) address
    matchMode: (NSString*) matchMode
    country: (NSString*) country
    completionHandler: (void (^)(PBTimezone* output, NSError* error)) handler;


/// Timezone By Location.
/// Identifies and retrieves the local time of any location in the world for a given latitude, longitude and time. The input and retrieved time format is in milliseconds.
///
/// @param timestamp Timestamp in miliseconds.
/// @param longitude Longitude of the location.
/// @param latitude Latitude of the location.
/// 
///  code:200 message:"successful operation"
///
/// @return PBTimezoneLocation*
-(NSNumber*) getTimezoneByLocationWithTimestamp: (NSString*) timestamp
    longitude: (NSString*) longitude
    latitude: (NSString*) latitude
    completionHandler: (void (^)(PBTimezoneLocation* output, NSError* error)) handler;



@end
