#import <Foundation/Foundation.h>
#import "PBGeoPropertyResponse.h"
#import "PBGeoPropertyResponses.h"
#import "PBGeoPropertyAddressRequest.h"
#import "PBGeoPropertyPBKeyResponse.h"
#import "PBGeoPropertyPBKeyResponses.h"
#import "PBGeoPropertyPBKeyRequest.h"
#import "PBApi.h"

/**
* Location Intelligence APIs
* Incorporate our extensive geodata into everyday applications, business processes and workflows.
*
* OpenAPI spec version: 6.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface PBLIAPIGeoPropertyServiceApi: NSObject <PBApi>

extern NSString* kPBLIAPIGeoPropertyServiceApiErrorDomain;
extern NSInteger kPBLIAPIGeoPropertyServiceApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Gets GeoPropertyResponse
/// Gets GeoPropertyResponse
///
/// @param address free form address text
/// 
///  code:200 message:"successful operation"
///
/// @return PBGeoPropertyResponse*
-(NSNumber*) getGeoPropertyByAddressWithAddress: (NSString*) address
    completionHandler: (void (^)(PBGeoPropertyResponse* output, NSError* error)) handler;


/// Gets GeoPropertyResponses
/// Gets GeoPropertyResponses
///
/// @param body  (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return PBGeoPropertyResponses*
-(NSNumber*) getGeoPropertyByAddressBatchWithBody: (PBGeoPropertyAddressRequest*) body
    completionHandler: (void (^)(PBGeoPropertyResponses* output, NSError* error)) handler;


/// Gets GeoPropertyResponse
/// Gets GeoPropertyResponse
///
/// @param pbKey free form text
/// 
///  code:200 message:"successful operation"
///
/// @return PBGeoPropertyPBKeyResponse*
-(NSNumber*) getGeoPropertyByPBKeyWithPbKey: (NSString*) pbKey
    completionHandler: (void (^)(PBGeoPropertyPBKeyResponse* output, NSError* error)) handler;


/// Gets GeoPropertyResponses
/// Gets GeoPropertyResponses
///
/// @param body  (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return PBGeoPropertyPBKeyResponses*
-(NSNumber*) getGeoPropertyByPBKeyBatchWithBody: (PBGeoPropertyPBKeyRequest*) body
    completionHandler: (void (^)(PBGeoPropertyPBKeyResponses* output, NSError* error)) handler;



@end
