#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Location Intelligence APIs
* Incorporate our extensive geodata into everyday applications, business processes and workflows.
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SWGCandidateRange.h"
#import "SWGFieldsMatching.h"
#import "SWGGeoPos.h"
#import "SWGGeocodeAddress.h"


@protocol SWGCandidate
@end

@interface SWGCandidate : SWGObject


@property(nonatomic) NSNumber* precisionLevel;

@property(nonatomic) NSString* formattedStreetAddress;

@property(nonatomic) NSString* formattedLocationAddress;

@property(nonatomic) NSString* identifier;

@property(nonatomic) NSString* precisionCode;

@property(nonatomic) NSString* sourceDictionary;

@property(nonatomic) SWGFieldsMatching* matching;

@property(nonatomic) SWGGeoPos* geometry;

@property(nonatomic) SWGGeocodeAddress* address;

@property(nonatomic) NSArray<SWGCandidateRange>* ranges;

@property(nonatomic) NSNumber* worldGeocoded;

@end
