#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Location Intelligence APIs
* Incorporate our extensive geodata into everyday applications, business processes and workflows.
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SWGAddress.h"
#import "SWGCensus.h"
#import "SWGLatLongFields.h"
#import "SWGSalesTax.h"
#import "SWGTaxJurisdiction.h"
#import "SWGUseTax.h"


@protocol SWGTaxResponse
@end

@interface SWGTaxResponse : SWGObject


@property(nonatomic) NSString* gnisCode;

@property(nonatomic) NSNumber* confidence;

@property(nonatomic) SWGTaxJurisdiction* jurisdiction;

@property(nonatomic) SWGAddress* matchedAddress;

@property(nonatomic) SWGSalesTax* salesTax;

@property(nonatomic) SWGUseTax* useTax;

@property(nonatomic) SWGCensus* census;

@property(nonatomic) SWGLatLongFields* latLongFields;

@end
